// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace PeasyMotion
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidPeasyMotionPackageString = "4fa9da7b-5f7c-4d43-8a46-9326a6eb6eab";
        public static Guid guidPeasyMotionPackage = new Guid(guidPeasyMotionPackageString);

        public const string guidPeasyMotionPackageCmdSetString = "921fde78-c60b-4458-af50-fbb52d4b6a63";
        public static Guid guidPeasyMotionPackageCmdSet = new Guid(guidPeasyMotionPackageCmdSetString);

        public const string guidImagesString = "3e6d0d87-f85a-45e7-bf87-a8f3a94c781b";
        public static Guid guidImages = new Guid(guidImagesString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int TopMenuGroup = 0x1020;
        public const int SubMenu = 0x1100;
        public const int SubMenuGroup = 0x1150;
        public const int PeasyMotionActivateId = 0x0100;
        public const int PeasyMotionSelectTextActivateId = 0x0101;
        public const int PeasyMotionLineJumpToWordBeginingId = 0x0102;
        public const int PeasyMotionLineJumpToWordEndingId = 0x0103;
        public const int PeasyMotionJumpToDocumentTab = 0x0104;
        public const int PeasyMotionJumpToLineBegining = 0x0105;
        public const int PeasyMotionTwoCharJump = 0x0106;
        public const int bmpHighlightText = 0x0001;
    }
}